export const AppActionTypes = {
  LOAD_REFERENCE_DATA_INIT: "LOAD_REFERENCE_DATA_INIT",
  LOAD_REFERENCE_DATA_SUCCESS: "LOAD_REFERENCE_DATA_SUCCESS",
  LOAD_REFERENCE_DATA_FAILURE: "LOAD_REFERENCE_DATA_FAILURE",
  SET_ALERT: "SET_ALERT",
  CLEAR_ALERT: "CLEAR_ALERT",
  SET_API_STATUS: "SET_API_STATUS",
  SET_ERROR: 'SET_ERROR',
  NULL: "NULL"
}