export const BudgetActionTypes = {
  LOAD_BUDGET_INIT: 'LOAD_BUDGET_INIT',
  LOAD_BUDGET_SUCCESS: 'LOAD_BUDGET_SUCCESS',
  LOAD_BUDGET_FAILURE: 'LOAD_BUDGET_FAILURE',
  LOAD_MONTH_YEARS_INIT: 'LOAD_MONTH_YEARS_INIT',
  LOAD_MONTH_YEARS_SUCCESS: 'LOAD_MONTH_YEARS_SUCCESS',
  LOAD_MONTH_YEARS_FAILURE: 'LOAD_MONTH_YEARS_FAILURE',
  LOAD_SUMMARY_INIT: 'LOAD_DAILY_SUMMARY_INIT',
  LOAD_SUMMARY_SUCCESS: 'LOAD_DAILY_SUMMARY_SUCCESS',
  LOAD_SUMMARY_FAILURE: 'LOAD_DAILY_SUMMARY_FAILURE',
  SORT_BUDGET: 'SORT_BUDGET'
}