export const MerchantActionTypes = {
  LOAD_MERCHANTS_INIT: 'LOAD_MERCHANTS_INIT',
  LOAD_MERCHANTS_SUCCESS: 'LOAD_MERCHANTS_SUCCESS',
  LOAD_MERCHANTS_FAILURE: 'LOAD_MERCHANTS_FAILURE',
  SORT_MERCHANTS: 'SORT_MERCHANTS'
}